---
version: '2'
services:

  mongodb:
    image: docker.sunet.se/eduid/mongodb
    expose:
      - 27017
    networks:
      dev:
    volumes:
      - ../data/mongodb:/data
      - ../mongodb/etc:/opt/eduid/etc:ro
      - ../mongodb/db-scripts:/opt/eduid/db-scripts:ro

  op:
    image: docker.sunet.se/se-leg/op
    expose:
      - 5000
    networks:
      dev:
        ipv4_address: 172.16.20.100
    ports:
      - "5000:5000"
    volumes:
      - ../op/etc:/op/etc:ro
      - ../demo/etc/ssl/rootCA.pem:/op/ssl/rootCA.pem:ro
      - ../data/op:/op/data
      - ../sources/se-leg-op:/opt/se-leg/se-leg-op:ro
    environment:
      - "SE_LEG_PROVIDER_SETTINGS=/op/etc/app_config.py"
      - "PYTHONPATH=/opt/se-leg/se-leg-op/src:/op/src/src"
      - "REQUESTS_CA_BUNDLE=/op/ssl/rootCA.pem"
    depends_on:
      - redis

  op_worker:
    image: docker.sunet.se/se-leg/op
    networks:
      dev:
        ipv4_address: 172.16.20.110
    volumes:
      - ../op/etc:/op/etc:ro
      - ../demo/etc/ssl/rootCA.pem:/op/ssl/rootCA.pem:ro
      - ../sources/se-leg-op:/opt/se-leg/se-leg-op:ro
    environment:
      # http://click.pocoo.org/5/python3/
      - "LC_ALL=C.UTF-8"
      - "LANG=C.UTF-8"
      - "PYTHONPATH=/op/etc:/opt/se-leg/se-leg-op/src:/op/src/src"
      - "REQUESTS_CA_BUNDLE=/op/ssl/rootCA.pem"
    depends_on:
      - op
    command: >
      /op/env/bin/rq worker -c worker_config

  redis:
    image: docker.sunet.se/eduid/redis
    networks:
      dev:
    volumes:
      - ../redis/etc:/etc/redis:ro
      - ../data/redis:/data

  rp:
    image: docker.sunet.se/se-leg/rp
    networks:
      dev:
        ipv4_address: 172.16.20.200
    volumes:
      - ../rp/etc:/rp/etc:ro
      - ../demo/etc/ssl/rootCA.pem:/rp/ssl/rootCA.pem:ro
      - ../sources/se-leg-rp:/opt/se-leg/se-leg-rp:ro
    environment:
      # http://click.pocoo.org/5/python3/
      - "LC_ALL=C.UTF-8"
      - "LANG=C.UTF-8"
      - "PYTHONPATH=/rp/etc:/opt/se-leg/se-leg-rp:/rp/src"
      - "REQUESTS_CA_BUNDLE=/rp/ssl/rootCA.pem"
    depends_on:
      - mongodb
      - op

  demo:
    image: docker.sunet.se/eduid/nginx
    expose:
      - 443
    networks:
      dev:
        ipv4_address: 172.16.20.210
    ports:
      - "443:443"
    depends_on:
      - rp
      - op
    volumes:
      - ../demo/etc/demo.conf:/etc/nginx/sites-enabled/default:ro
      - ../demo/etc/ssl/:/etc/ssl/:ro
      - ../demo/www-data/:/var/www/:ro

networks:
  dev:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.20.0/24
        gateway: 172.16.20.1
