---
version: '2'
services:

  mongodb:
    image: docker.sunet.se/eduid/mongodb
    expose:
      - 27017
    networks:
      dev:
        ipv4_address: 172.16.20.10
    volumes:
      - ../data/mongodb:/data
      - ../mongodb/etc:/opt/eduid/etc:ro
      - ../mongodb/db-scripts:/opt/eduid/db-scripts:ro

  op:
    image: docker.sunet.se/se-leg/op
    expose:
      - 5000
    networks:
      dev:
        ipv4_address: 172.16.20.100
    ports:
      - "5000:5000"
    volumes:
      - ../op/etc:/op/etc:ro
      - ../demo/etc/ssl/ca-certificates.crt:/op/ssl/rootCA.pem:ro
      - ../data/op:/op/data
      - ../op/logs:/var/log/op
      - ../sources/se-leg-op:/opt/se-leg/se-leg-op:ro
    environment:
      - "SE_LEG_PROVIDER_SETTINGS=/op/etc/app_config.py"
      - "PYTHONPATH=/opt/se-leg/se-leg-op/src:/op/src/src"
      - "REQUESTS_CA_BUNDLE=/op/ssl/rootCA.pem"
    depends_on:
      - redis

  op_worker:
    image: docker.sunet.se/se-leg/op
    networks:
      dev:
        ipv4_address: 172.16.20.110
    volumes:
      - ../op/etc:/op/etc:ro
      - ../demo/etc/ssl/ca-certificates.crt:/op/ssl/rootCA.pem:ro
      - ../op/logs/worker:/var/log/op
      - ../sources/se-leg-op:/opt/se-leg/se-leg-op:ro
    environment:
      # http://click.pocoo.org/5/python3/
      - "LC_ALL=C.UTF-8"
      - "LANG=C.UTF-8"
      - "SE_LEG_PROVIDER_SETTINGS=/op/etc/app_config.py"
      - "PYTHONPATH=/op/etc:/opt/se-leg/se-leg-op/src:/op/src/src"
      - "REQUESTS_CA_BUNDLE=/op/ssl/rootCA.pem"
    depends_on:
      - op
    command: >
      /op/env/bin/rq worker -c worker_config

  redis:
    image: docker.sunet.se/eduid/redis
    networks:
      dev:
    volumes:
      - ../redis/etc:/etc/redis:ro
      - ../data/redis:/data

  se_leg_rp:
    image: docker.sunet.se/se-leg/rp
    networks:
      dev:
        ipv4_address: 172.16.20.200
    volumes:
      - ../se-leg-rp/etc:/rp/etc:ro
      - ../demo/etc/ssl/ca-certificates.crt:/rp/ssl/rootCA.pem:ro
      - ../sources/se-leg-rp:/opt/se-leg/se-leg-rp:ro
    environment:
      # http://click.pocoo.org/5/python3/
      - "LC_ALL=C.UTF-8"
      - "LANG=C.UTF-8"
      - "PYTHONPATH=/rp/etc:/opt/se-leg/se-leg-rp:/rp/src"
      - "REQUESTS_CA_BUNDLE=/rp/ssl/rootCA.pem"
    depends_on:
      - mongodb
      - op

  nstic_rp:
    image: docker.sunet.se/se-leg/rp
    networks:
      dev:
        ipv4_address: 172.16.20.201
    volumes:
      - ../nstic-rp/etc:/rp/etc:ro
      - ../demo/etc/ssl/ca-certificates.crt:/rp/ssl/rootCA.pem:ro
      - ../sources/se-leg-rp:/opt/se-leg/se-leg-rp:ro
    environment:
      # http://click.pocoo.org/5/python3/
      - "LC_ALL=C.UTF-8"
      - "LANG=C.UTF-8"
      - "PYTHONPATH=/rp/etc:/opt/se-leg/se-leg-rp:/rp/src"
      - "REQUESTS_CA_BUNDLE=/rp/ssl/rootCA.pem"
    depends_on:
      - mongodb
      - op

  ra_sp:
    container_name: rasp.se-leg.docker
    image: docker.sunet.se/sp-swamid
    networks:
      dev:
        ipv4_address: 172.16.20.204
    expose:
      - 80
      - 443
    volumes:
      - ../se-leg-ra-sp/etc/apache2/sites-available:/etc/apache2/sites-available:ro
      - ../se-leg-ra-sp/etc/shibboleth/shibboleth2.xml:/etc/shibboleth/shibboleth2.xml:ro
      - ../se-leg-ra-sp/etc/shibboleth/idp.xml:/etc/shibboleth/idp.xml:ro
      - ../se-leg-ra-sp/etc/ssl:/etc/ssl:ro
      - ../se-leg-ra-sp/etc/shibboleth/shibd.logger:/etc/shibboleth/shibd.logger:ro
      - ../se-leg-ra-sp/log:/var/log/shibboleth
      - ra-static-volume:/ra/static
    environment:
      - "HOSTNAME=rasp.se-leg.docker"
      - "SP_HOSTNAME=rasp.se-leg.docker"
      - "DEFAULT_LOGIN="
      - "METADATA_SIGNER="
    depends_on:
      - idp
      - ra

  ra:
    image: docker.sunet.se/se-leg/ra
    networks:
      dev:
    expose:
      - 5000
    volumes:
      - ../se-leg-ra/etc/app_config.py:/ra/etc/app_config.py
      - ../demo/etc/ssl/ca-certificates.crt:/ra/ssl/rootCA.pem:ro
      - ra-static-volume:/ra/static
      - ../sources/se-leg-ra:/opt/se-leg/se-leg-ra:ro
    environment:
      - "PYTHONPATH=/opt/se-leg/se-leg-ra:/ra/src"
      - "REQUESTS_CA_BUNDLE=/ra/ssl/rootCA.pem"
    depends_on:
      - mongodb

  idp:
    container_name: idp.se-leg.docker
    image: docker.sunet.se/sunet/docker-pysaml2-idp
    expose:
      - 443
    networks:
      dev:
        ipv4_address: 172.16.20.205
    volumes:
      - ../pysaml2-idp/etc/:/opt/pysaml2-idp/etc/
      - ../pysaml2-idp/log/idp.log:/tmp/src/pysaml2/example/idp2/idp.log
    environment:
      - "DATA_DIR=/opt/pysaml2-idp/etc/"

  demo:
    image: docker.sunet.se/eduid/nginx
    expose:
      - 443
    networks:
      dev:
        ipv4_address: 172.16.20.210
    ports:
      - "127.0.0.1:443:443"
    depends_on:
      - se_leg_rp
      - nstic_rp
      - op
    volumes:
      - ../demo/etc/demo.conf:/etc/nginx/sites-enabled/default:ro
      - ../demo/etc/ssl/:/etc/ssl/:ro
      - ../demo/www-data/:/var/www/:ro

volumes:
  ra-static-volume:

networks:
  dev:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.20.0/24
        gateway: 172.16.20.1
