---
version: '2'
services:

  etcd:
    image: docker.sunet.se/library/etcd:v2.2.5
    expose:
      - 2379
      - 2380
      - 4001
    networks:
      selegdev:
        ipv4_address: 172.16.20.254
    command: >
      -name etcd
      -advertise-client-urls http://172.16.20.254:2379,http://172.16.20.254:4001
      -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001
      -initial-advertise-peer-urls http://172.16.20.254:2380
      -listen-peer-urls http://0.0.0.0:2380
      -initial-cluster-token etcd-cluster-1
      -initial-cluster etcd=http://172.16.20.254:2380
      -initial-cluster-state new
      -data-dir /data
    volumes:
      - ./data/etcd:/data

networks:
  selegdev:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.20.0/24
        gateway: 172.16.20.1
