---
version: '2'
services:

  etcd:
    image: docker.sunet.se/library/etcd:v2.2.5
    expose:
      - 2379
      - 2380
      - 4001
    networks:
      dev:
        ipv4_address: 172.16.20.254
    command: >
      -name etcd
      -advertise-client-urls http://172.16.20.254:2379,http://172.16.20.254:4001
      -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001
      -initial-advertise-peer-urls http://172.16.20.254:2380
      -listen-peer-urls http://0.0.0.0:2380
      -initial-cluster-token etcd-cluster-1
      -initial-cluster etcd=http://172.16.20.254:2380
      -initial-cluster-state new
      -data-dir /data
    volumes:
      - ../data/etcd:/data

  mongodb:
    image: docker.sunet.se/eduid/mongodb
    expose:
      - 27017
    networks:
      dev:
    volumes:
      - ../data/mongodb:/data
      - ../mongodb/etc:/opt/eduid/etc:ro
      - ../mongodb/db-scripts:/opt/eduid/db-scripts:ro

  op:
    image: docker.sunet.se/se-leg/op
    expose:
      - 5000
    networks:
      dev:
        ipv4_address: 172.16.20.100
    volumes:
      - ../op/etc:/op/etc:ro
      - ../data/op:/op/data
      - ../sources/se-leg-op:/opt/se-leg/se-leg-op:ro
    environment:
      - "SE_LEG_PROVIDER_SETTINGS=/op/etc/app_config.py"
      - "PYTHONPATH=/opt/se-leg/se-leg-op/src:/op/src/src"
    depends_on:
      - redis

  redis:
    image: docker.sunet.se/eduid/redis
    networks:
      dev:
    volumes:
      - ../redis/etc:/etc/redis:ro
      - ../data/redis:/data

  rp:
    image: docker.sunet.se/eduid/eduid-oidc-proofing
    networks:
      dev:
        ipv4_address: 172.16.20.200
    environment:
      - "ETCD_HOST=etcd"
      - "PYTHONPATH=/opt/eduid/src/eduid-webapp/src:/opt/eduid/eduid-webapp/src"
    depends_on:
      - mongodb
      - etcd
      - bootstrap
      - op
    volumes:
      - ../sources/eduid-webapp:/opt/eduid/src/eduid-webapp:ro

  demo:
    image: docker.sunet.se/eduid/nginx
    expose:
      - 80
    networks:
      dev:
        ipv4_address: 172.16.20.210
    depends_on:
      - rp
      - op
    volumes:
      - ../demo/etc/demo.conf/:/etc/nginx/sites-enabled/default:ro
      - ../demo/www-data/:/var/www/:ro

  bootstrap:
    image: docker.sunet.se/eduid/eduid-webapp
    networks:
      dev:
    depends_on:
      - etcd
    volumes:
      - ../bootstrap:/bootstrap:ro
    command: >
      /opt/eduid/bin/python /bootstrap/etcd_config_bootstrap.py -v --host etcd -c /bootstrap/conf.yaml


networks:
  dev:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.20.0/24
        gateway: 172.16.20.1
